name: 'Create Pull Request automatically'
description: 'Auto create pull request from an implicit source to an explicit base'
branding:
  icon: 'git-pull-request'
  color: 'green'
inputs:
  git-token:
    description: 'Token able to create Pull Requests'
    required: true
  base-branch:
    description: 'The branch where you want your changes'
    required: true
  head-branch:
    description: 'The branch where you made yout changes'
    required: false
    default: 'The branch that triggers the action'
  title:
    description: 'The title of the PR'
    required: false
    default: 'Auto created Pull Request'
  body:
    description: 'The body of the PR'
    required: false
    default: 'This PR was created by a Github Action'
outputs:
    pull_request_url:
      description: 'The generated Pull Request'
runs:
  using: 'node16'
  main: 'index.js'
